# Generated by Django 2.2.3 on 2020-02-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcweblayout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='time',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='topic',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='chapter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='part',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
